// Generated by https://quicktype.io

export interface DashboradSummaryRes {
    numberOfOrders:        number;
    paidOrders:            number;
    notPaidOrders:         number;
    numberOfClients:       number;
    numberOfProducts:      number;
    productWithNoInvetory: number;
    lowInventory:          number;
}
